services:
  asterisk:
    image: bytebrigand/asterisk:22.3.0
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-20000:10000-20000/udp"
    volumes:
      - ./extensions.conf:/etc/asterisk/extensions.conf:ro
      - ./pjsip.conf:/etc/asterisk/pjsip.conf:ro
      - ./sounds:/var/lib/asterisk/sounds/custom
    restart: unless-stopped
    network_mode: host
